name: build-and-publish-docs

on:
  push:
    branches:
      - main

jobs:
  build-and-publish-docs:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
    
    steps:
      - name: Step 1. Checkout repository
        uses: actions/checkout@v3
      
      - name: Step 2. Setup python environment on virtual machine 
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      
      - name: Step 3. Install dependencies
        run: |
          pip install -e .
          pip install sphinx furo
      
      - name: Step 4. Build documentation with Sphinx
        run: |
          sphinx-apidoc --output-dir ./docs ./src/sphinxy --separate
          sphinx-build ./docs ./docs/_build/html
      
      - name: Step 5. Deploy using Github pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html
          force_orphan: true