name: print-hello-world

on:
  push:
    branches:
      - main

jobs:
  print-hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1. Print hello world to terminal
        run: echo "Hello, World!"